version: "3"

services:
  vote:
    image: gauravbajpai9211/examplevotingapp_vote
    ports:
      - "5000:80"
    networks:
      - front-tier
      - back-tier

  redis:
    image: redis:alpine
    container_name: redis
    ports: ["6379"]
    networks:
        - back-tier

  worker:
    image: gauravbajpai9211/examplevotingapp_worker:java
    container_name: worker
    depends_on:
        - "redis"
        - "db"
    networks:
        - back-tier

  db:
    image: postgres:9.4
    container_name: db
    volumes: 
        - "db-data:/var/lib/postgresql/data"
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
    networks:
      - back-tier

  result:
    image: gauravbajpai9211/examplevotingapp_result
    container_name: result
    ports:
      - "5001:80"
      - "5858:5858"
    networks:
      - front-tier
      - back-tier
volumes:
    db-data:
      
networks:
    front-tier:
    back-tier: